[workspace]
resolver = "2"
members = ["cli",
    "core/*"
]

[workspace.dependencies]
clap = { version = "4.5.17", features = ["derive"] }
tracing = { version = "0.1.40" }
tracing-subscriber = { version = "0", features = ["env-filter"] }
tracing-error = { version = "0.2.0", features = ["traced-error"] }
thiserror = "1.0.63"
termcolor = "1.4.1"

# Pulse Crates
pulse_ast = { path = "core/ast" }
pulse_lexer = { path = "core/lexer" }
pulse_core = { path = "core/core" }
