[package]
name = "pulse_core"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = { workspace = true }
tracing = { workspace = true }
termcolor = { workspace = true }

# Pulse Crates
pulse_ast = { workspace = true }