[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-error = { workspace = true }
termcolor = { workspace = true }

# Pulse Crates
pulse_core = { workspace = true }
