[package]
name = "pulse_core"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = { workspace = true }
colored = { workspace = true }
log = { workspace = true }
indexmap = { workspace = true }
rustc-hash = "2.0.0"
lazy_static = { workspace = true }